from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _run_script(
    script: str, *paths: str, cwd: Path | None = None
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(ROOT / "scripts" / script), *paths],
        cwd=cwd or ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def test_block_env_files_rejects_env_names(tmp_path):
    result = _run_script("block-env-files.sh", ".env", "app/.env.prod", cwd=tmp_path)
    assert result.returncode == 1
    assert ".env" in result.stderr


def test_block_claude_generated_rejects_agent_artifacts(tmp_path):
    result = _run_script("block-claude-generated.sh", ".omx/context/report.md", cwd=tmp_path)
    assert result.returncode == 1
    assert ".omx/context/report.md" in result.stderr


def test_check_generated_markdown_rejects_known_generated_names(tmp_path):
    impl = tmp_path / "IMPLEMENTATION.md"
    impl.write_text("generated by codex")

    result = subprocess.run(
        ["python3", str(ROOT / "scripts" / "check_generated_markdown.py"), str(impl)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert "IMPLEMENTATION.md" in result.stderr


def test_check_generated_markdown_rejects_marker_based_markdown(tmp_path):
    note = tmp_path / "notes.md"
    note.write_text(
        "# Task Statement\nGenerated by oh-my-codex\n# Desired Outcome\nKeep this local.\n"
    )

    result = subprocess.run(
        ["python3", str(ROOT / "scripts" / "check_generated_markdown.py"), str(note)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert "notes.md" in result.stderr


def test_check_generated_markdown_allows_readme(tmp_path):
    readme = tmp_path / "README.md"
    readme.write_text("Regular project documentation")

    result = subprocess.run(
        ["python3", str(ROOT / "scripts" / "check_generated_markdown.py"), str(readme)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
