from __future__ import annotations

from pathlib import Path

from repo_hygiene import inspect_markdown_path, markdown_has_generated_markers


def test_markdown_has_generated_markers_requires_multiple_hits():
    assert markdown_has_generated_markers("# Task Statement\nCodex\n") is True
    assert markdown_has_generated_markers("# Task Statement\nNormal notes only\n") is False


def test_inspect_markdown_path_flags_generated_name(tmp_path: Path):
    path = tmp_path / "IMPLEMENTATION.md"
    path.write_text("plain text")
    assert inspect_markdown_path(path) == "suspicious generated markdown filename"


def test_inspect_markdown_path_flags_generated_content(tmp_path: Path):
    path = tmp_path / "notes.md"
    path.write_text(
        "# Task Statement\n# Desired Outcome\nGenerated by Codex for local planning only.\n"
    )
    assert inspect_markdown_path(path) == "generated-planning/report content markers"


def test_inspect_markdown_path_allows_regular_readme(tmp_path: Path):
    path = tmp_path / "README.md"
    path.write_text("# Project\nNormal documentation.\n")
    assert inspect_markdown_path(path) is None
